services:
  web:
    build: ./back_1erParcial/
    container_name: django_backend
    command: >
      python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=p1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./back_1erParcial:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - frontend
    networks:
      - backend
      - frontend

  frontend:
    build: ./front_1erParcial/
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://web:8000
    networks:
      - frontend
      - backend

networks:
  backend:
    external: true
  frontend:
    driver: bridge
